#
# document - ドキュメントのビルド、デプロイ
#
name: document

# 実行条件
on:
  push:
    branches: [develop]
    paths:
      - "src/**"
      - "docs/source/**"

  workflow_run:
    workflows: [release]
    types: [completed]

jobs:
  document:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install repository to make it usable as package
        run: |
          python3 -m pip install --upgrade pip
          pip install .

      - name: Install dependencies for sphinx
        run: |
          pip install sphinx sphinx_rtd_theme sphinx-multiversion

      - name: Create API documentation using sphinx-apidoc
        run: |
          sphinx-apidoc \
          --force \
          --module-first \
          -d 1 \
          --templatedir="docs/source/_templates" \
          -o docs/source \
          ./src/blueprintpy \
          "*internal_templates"

      - name: Remove unused document sources
        run: |
          cd docs/source
          rm -f modules.rst blueprintpy.rst

      - name: Build HTML documentation using sphinx-multiversion
        run: sphinx-multiversion docs/source docs/build

      - name: Add root HTML source (for redirect to release branch)
        run: cp docs/source/redirect.html docs/build/index.html

      - name: Git setup
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Switch to orphan branch for deploying to GitHub Pages
        run: |
          git checkout --orphan gh-pages
          git reset --hard
          git pull origin gh-pages

      - name: Commit and push built documents
        run: |
          for document in $( ls docs/build ); do
              rm -rf ./${document}
              mv docs/build/${document} .
              git add ${document}
          done
          touch .nojekyll
          git add .nojekyll
          git diff --quiet && git diff --staged --quiet || git commit -am "[Update] *automated* documents"
          git push origin gh-pages
