#
# publish package to pypi
#
name: pypi

on:
  workflow_dispatch:

jobs:
  branch_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check if the workflow was called from master branch
        run: |
          CURRENT=`git branch | grep "^*" | sed -e "s/^\* //"`
          CHECK="release"
          [ $CURRENT = $CHECK ]

  publish_release:
    needs: branch_check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get current version
        run: |
          VERSION=`cat setup.cfg | sed -rn "s/version=(.*)/\1/p"`
          echo "current_full_version=${VERSION}" >> $GITHUB_ENV

      - name: Get hash of last commit
        run: echo "latest_commit_hash=`git rev-parse HEAD`" >> $GITHUB_ENV

      - name: Create draft release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:
          tag_name: v${{ env.current_full_version }}
          target_commitish: ${{ env.latest_commit_hash }}
          draft: true
          prerelease: false
          generate_release_notes: true

  publish_to_pypi:
    needs: branch_check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install pypa/build
        run: python -m pip install build --user

      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
