#
# Release
#

name: release

on:
  workflow_run:
    workflows:
      - prepare for release
    branches:
      - release
    types:
      - completed

jobs:
  publish_release:
    needs: auto_versioning
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get current version
        run: |
          VERSION=`cat setup.cfg | sed -rn "s/version=(.*)/\1/p"`
          echo "current_full_version=${VERSION}" >> $GITHUB_ENV
          echo "version ${VERSION} will be released!"

      - name: Get hash of last commit
        run: echo "latest_commit_hash=`git rev-parse HEAD`" >> $GITHUB_ENV

      - name: Create draft release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:
          tag_name: v${{ env.current_full_version }}
          target_commitish: ${{ env.latest_commit_hash }}
          draft: false
          prerelease: false
          generate_release_notes: true

  publish_to_pypi:
    needs: auto_versioning
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install pypa/build
        run: python -m pip install build --user

      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
