#
# release - GitHub, PyPIへのリリース
#
name: release

# 実行条件:
#  - versioningワークフロー完了 @release
on:
  workflow_run:
    workflows: [versioning]
    branches: [release]
    types: [completed]

jobs:
  # リリースバージョンを取得
  get_version_to_release:
    runs-on: ubuntu-latest

    steps:
      # リリースブランチをチェックアウト
      - uses: actions/checkout@v3
        with:
          ref: "release"

      # コミットメッセージから次期バージョンを探る
      - name: Get next version from commit history
        run: |
          NEXT_VERSION=`bash ./ci_scripts/vercalc.sh | tail -n 1`
          echo "NEXT_VERSION=${NEXT_VERSION}" >> $GITHUB_ENV

  # GitHubリリース発行
  release_to_github:
    runs-on: ubuntu-latest
    needs: get_version_to_release

    steps:
      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:
          tag_name: v${{ env.NEXT_VERSION }}
          draft: true
          prerelease: false
          generate_release_notes: true

  # PyPIリリース発行
  release_to_pypi:
    runs-on: ubuntu-latest
    needs: get_version_to_release

    steps:
      # リリースブランチをチェックアウト
      - uses: actions/checkout@v3
        with:
          ref: "release"

      # Pythonセットアップ
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # ライブラリのビルド
      - name: Install pypa/build
        run: python -m pip install build --user

      # アップロード準備
      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/

      # # PyPIへアップロード
      # - name: Publish to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     password: ${{ secrets.PYPI_API_TOKEN }}
